# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab43ea9e9a37990b1ca2eda3bb5eed0970e487633de070aa9c3f2d150889126d4e6fe41af0e851dbe31c158930a87dcf3b5bc1a655fcc80c2a5047e181ef808

test:
  secret_key_base: 5af37bc8853d7d6211d244b733389755fc41007f1759ee573b08cd674beac0faf16a8f71c343ca5ed4128807e7ddaf7567ed2a5fc0937b5e0d189d64d296fe30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
